Repository kubernetes/kubernetes-anywhere, pull requests merged in 2018-08, with the labels that each got.

#544 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, size/S

#554 Remove the deprecated --skip-preflight-checks for kubeadm
  phase2/kubeadm/configure-vm-kubeadm-master.sh
  phase2/kubeadm/configure-vm-kubeadm-node.sh
  phase2/kubeadm/do
Labels: cncf-cla: yes, lgtm, size/XS

#540 Typo fix: specifed->specified
  phase1/vsphere/README.md
Labels: cncf-cla: yes, size/XS

#509 Fix typo under the Phase 3 header
  README.md
Labels: cncf-cla: yes, size/XS

#557 phase1-gce: make it possible to use GOOGLE_APPLICATION_CREDENTIALS
  phase1/gce/do
Labels: cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS
