Repository kubernetes/kubernetes-anywhere, pull requests merged in 2018-10, with the labels that each got.

#569 phase2: handle v1alpha3 kubeadm config
  phase2/kubeadm/configure-vm-kubeadm-master.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, sig/cluster-lifecycle, size/L

#558 Vsphere: field does not exist: insecure
  phase1/vsphere/vSphere.jsonnet
Labels: cncf-cla: yes, size/XS

#571 kubeadm v1beta1 config
  phase2/kubeadm/configure-vm-kubeadm-master.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, sig/cluster-lifecycle, size/M

#572 kubeadm: decide on config type based on kubeadm client version
  phase2/kubeadm/configure-vm-kubeadm-master.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/S
